#!/bin/sh
#Use this to add packages to your machine when running wu_setup_dev

# Install C++11
cd /etc/yum.repos.d
wget http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo 
yum --enablerepo=testing-1.1-devtools-6 --skip-broken install devtoolset-1.1-gcc devtoolset-1.1-gcc-c++

# Install rapidfire support
yum install openldap-devel

#upgrade to ZeroMQ/3.2.2
yum remove -y zeromq zeromq-devel
wget http://download.zeromq.org/zeromq-3.2.2.tar.gz
tar zxvf zeromq-3.2.2.tar.gz && cd zeromq-3.2.2
./configure
make && make install
cp /usr/local/lib/libzmq* /usr/lib64/

# Install Python 2.7.6
# install interpreter
cd /code/py
wget http://python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz --no-check-certificate
tar xf Python-2.7.6.tar.xz
cd Python-2.7.6
yum install zlib-devel
yum install openssl-devel
./configure --prefix=/usr/local --enable-unicode=ucs4 --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
make && make altinstall
# install pip (python module management)
wget https://bootstrap.pypa.io/ez_setup.py -O - | python2.7
easy_install-2.7 pip
# install necessary modules
pip2.7 install requests
pip2.7 install -I progressbar==2.2
pip2.7 install simplemysql
pip2.7 install jenkinsapi
pip2.7 install redis
pip2.7 install dotmap
pip2.7 install numpy
pip2.7 install pymongo
pip2.7 install cluster
pip2.7 install tzlocal
pip2.7 install python-dateutil
pip2.7 install frozendict
pip2.7 install BeautifulSoup4
pip2.7 install simplemysql
pip2.7 install pycrypto
# delete unneeded python installation files
cd /code/py/
rm -rf /code/py/Python-2.7.6
rm -rf /code/py/Python-2.7.6.tar.xz*

# Install Python 3
# install interpreter
cd /code/py
wget https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz --no-check-certificate
tar xf Python-3.5.1.tar.xz
cd Python-3.5.1
yum install openssl
yum install openssl-devel
./configure --enable-shared --prefix=/usr --with-ensurepip=install
make install
ln -s /usr/lib/libpython3.5m.so.1.0 /usr/lib64/libpython3.5m.so.1.0
# install necessary modules
pip3 install dotmap
pip3 install six
pip3 install modernize
pip3 install pycrypto
pip3 install python-dateutil
pip3 install tzlocal
pip3 install requests
pip3 install bs4
pip3 install pymongo
pip3 install numpy
pip3 install redis
pip3 install jenkinsapi
pip3 install sh
pip3 install pygal
pip3 install scipy
# delete unneeded python installation files
cd /code/py/
rm -rf /code/py/Python-3.5.1
rm -rf /code/py/Python-3.5.1.tar.xz*

# Install NPM
yum install npm

